# Generated by Django 2.2.3 on 2019-11-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_model',
            name='m_id',
        ),
    ]
