# Generated by Django 2.2.3 on 2019-11-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Log', '0002_remove_product_model_m_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_log',
        ),
        migrations.DeleteModel(
            name='MarchantModel',
        ),
        migrations.DeleteModel(
            name='Product_Model',
        ),
    ]
