# Generated by Django 2.2.3 on 2019-11-10 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Log', '0005_product_model_m_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_model',
            name='m_id',
        ),
    ]
