# Generated by Django 2.2.3 on 2019-11-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerdata',
            name='id_no',
        ),
    ]
